export const CHANGE_DATES = 'TABLE/CHANGE_DATES'
export const SAVE_TABLE_DATA = 'TABLE/SAVE_TABLE_DATA'
export const SAVE_SALARY_DATA = 'SALARY/SAVE_SALARY_DATA'
export const SAVE_TOTAL_SUM = 'SALARY/SAVE_TOTAL_SUM'

export const SHOW_SAVE_MODAL = 'MODAL/SHOW_SAVE_MODAL'
export const HIDE_SAVE_MODAL = 'MODAL/HIDE_SAVE_MODAL'
export const DISABLE_MODAL_BTN = 'MODAL/DISABLE_MODAL_BTN'
export const ENABLE_MODAL_BTN = 'MODAL/ENABLE_MODAL_BTN'

export const SAVE_DATE = 'DATE/SAVE_DATE'
